name: Test All Builds

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:

jobs:
  build-default:
    name: Build (LineageOS)
    uses: ./.github/workflows/build.yml
    with:
      kernel_type: LineageOS
      kpm_support: true
      susfs_support: true
      bbg_support: true
      susfs_force: false
